Repository CodeForAfrica/outbreak.AFRICA, pull requests merged in 2021-02, with the labels that each got.

#114 [HotFix] Configurable domain
  .env.tmpl
  src/config.js
Labels: bug, enhancement

#115 [HotFix] Configurable Dashboard URL
  .env.tmpl
  package.json
  src/config.js
Labels: dependencies, enhancement

#116 [Documentation] Add Setup/Install Instructions
  README.md
Labels: documentation
